---
- name: this playbook install httpd
  hosts: all
  become: true
  # gather_facts: no
  tasks:
  - name: install package
    yum:
      name: httpd
      state: installed
      tags: install_apache
    

  - name: start apache
    service:
      name: httpd
      state: started
      tags: start_apache
     

    

