---
- name: this playbook uninstall httpd
  hosts: all 
  become: true
  gather_facts: no
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped 

  - name: uninstall httpd
    yum: 
      name: httpd
      state: removed
    
